### PR TITLE
Include generated parser in .gitignore

### PR DESCRIPTION
**Pull request by CharlesTaylor7**
@warrenseine I think this will make diffs and merges less noisy. The parser takes about 7 seconds to generate on my machine, so I'm not concerned with that. What do you think?

### CODE REVIEW

**Comment by warrenseine** [comment]
I haven’t checked the details, but I’m pretty sure you need to generate the parser first in the Travis build command to make Travis happy.

I generally agree that generated files shouldn’t be checked in. I initially ignored these generated files, but then I checked them in so you don’t need `antlr4` to start working on the project. I’ll try to remember if there is another legitimate reason to keep them.

**Comment by CharlesTaylor7** [comment]
So if I can get Travis to generate the parser, would you be ok with this change?

The amount one can contribute to this project without updating the grammar files seems really limited to me. It basically limits you to modifying the printing rules, unless I'm missing something.

**Comment by warrenseine** [comment]
Yes.

**Comment by warrenseine** [comment]
I’d prefer to have a command to fetch the `.jar` instead of committing it. Can you make that change?

**Comment by CharlesTaylor7** [comment]
@warrenseine It's a been a busy couple of days, but I've got something now. Let me know what you think.

**Review by warrenseine — APPROVED** [review]

**Comment by warrenseine** [comment]
Thanks!

**Pull request merged**
